version: '3'
services:
    loadbalancer:
        ports:
            - "5000:5000"
        image: load_balancer

    worker1:
        hostname: worker1
        image: worker
        restart: always
        depends_on:
            - rabbitmq
            - rabbitmq2
        environment:
            HOSTNAME: rabbitmq
        expose:
            - 5672
            
    worker2:
        hostname: worker2
        image: worker
        restart: always
        depends_on:
            - rabbitmq
            - rabbitmq2
        environment:
            HOSTNAME: rabbitmq2
        expose:
            - 5672

    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:3-management
        expose:
            - 5672

    rabbitmq2:
        hostname: rabbitmq2
        image: rabbitmq:3-management
        expose:
            - 5672


