version: '3'
services:
    loadbalancer:
        ports:
            - "5000:5000"
        image: load_balancer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        expose:
            - 5000

    stresstesting:
        ports:
            - "5011:5011"
        image: sts

    worker1:
        hostname: worker1
        image: worker
        restart: always
        depends_on:
            - rabbitmq1
            - rabbitmq2
        environment:
            HOSTNAME: rabbitmq1
            PYTHONUNBUFFERED: 1
        expose:
            - 5672
            
    worker2:
        hostname: worker2
        image: worker
        restart: always
        depends_on:
            - rabbitmq1
            - rabbitmq2
        environment:
            HOSTNAME: rabbitmq2
            PYTHONUNBUFFERED: 1
        expose:
            - 5672

    worker3:
        hostname: worker3
        image: worker
        restart: always
        depends_on:
            - rabbitmq1
            - rabbitmq2
        environment:
            HOSTNAME: rabbitmq1
            PYTHONUNBUFFERED: 1
        expose:
            - 5672

    worker4:
        hostname: worker3
        image: worker
        restart: always
        depends_on:
            - rabbitmq1
            - rabbitmq2
        environment:
            HOSTNAME: rabbitmq2
            PYTHONUNBUFFERED: 1
        expose:
            - 5672

    rabbitmq1:
        hostname: rabbitmq1
        image: rabbitmq:3-management
        expose:
            - 5672

    rabbitmq2:
        hostname: rabbitmq2
        image: rabbitmq:3-management
        expose:
            - 5672


